include: package:pedantic/analysis_options.1.11.0.yaml

linter:
  rules:
    prefer_relative_imports: false
    always_use_package_imports: false
    public_member_api_docs: false

analyzer:
  errors:
    missing_required_param: error
