name: defuncart_github_io
description: The personal website of James Leahy.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  iframes:
    path: modules/iframes
  flutter_html: ^1.1.1
  markdown: ^3.0.0
  resume:
    path: modules/resume
  blog:
    path: modules/blog

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/common/icons/
    - assets/common/social_links/
    - assets/apps/caogacaoga/
    - assets/apps/derdiedas/
    - assets/apps/common/
    - assets/home/
    - assets/music/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        
