name: defuncart_github_io
description: The personal website of James Leahy.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  url_launcher:
  iframes:
    path: modules/iframes
  flutter_html:
  markdown:
  resume:
    path: modules/resume
  journal:
    path: modules/journal

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/common/icons/
    - assets/common/social_links/
    - assets/apps/caogacaoga/
    - assets/apps/derdiedas/
    - assets/apps/common/
    - assets/home/
    - assets/music/gray_dawn/
    - assets/music/strawberry_complexity/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        
