name: defuncart_github_io
description: The personal website of James Leahy.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  url_launcher:
  iframes:
    path: modules/iframes
  # flutter_html:
  markdown: ^4.0.0
  resume:
    path: modules/resume

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

# dependency_overrides:
  # chewie_audio: ^1.2.0
  # # flutter_html: ^1.3.0
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html

flutter:
  uses-material-design: true
  assets:
    - assets/common/icons/
    - assets/common/social_links/
    - assets/apps/caogacaoga/
    - assets/apps/derdiedas/
    - assets/apps/common/
    - assets/home/
    - assets/music/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        
