name: defuncart_github_io
description: The personal website of James Leahy.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  iframes:
    path: modules/iframes

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/common/social_links/
    - assets/home/
    - assets/music/
