name: defuncart_github_io
description: The personal website of James Leahy.
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  jaspr: ^0.18.0
  jaspr_router: ^0.6.4

dev_dependencies:
  build_runner: ^2.4.15
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1
  jaspr_tailwind: ^0.3.3
  jaspr_web_compilers: ^4.1.1
  lints: ^5.0.0
  test:

jaspr:
  mode: static
