name: journal
description: A multi-category blog journal built using Flutter.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter:
  iframes:
    path: ../iframes
  # unicorndial: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - packages/journal/assets/photography/2022-09-25.png
    - packages/journal/assets/photography/2022-03-24.png
    - packages/journal/assets/photography/2021-10-30.png
    - packages/journal/assets/photography/2021-10-02.png
    - packages/journal/assets/photography/2021-06-13.png
    - packages/journal/assets/photography/2021-06-05.png
    - packages/journal/assets/photography/2021-05-17.png
    - packages/journal/assets/photography/2021-05-02.png
    - packages/journal/assets/photography/2021-04-06.png
    - packages/journal/assets/photography/2021-03-10.png
    - packages/journal/assets/photography/2021-02-10.png
    - packages/journal/assets/photography/2021-02-09.png
    - packages/journal/assets/photography/2021-02-06.png
    - packages/journal/assets/photography/2020-09-13.png
    - packages/journal/assets/photography/2020-09-11.png
    - packages/journal/assets/photography/2020-08-18.png
    - packages/journal/assets/photography/2020-08-10.png
    - packages/journal/assets/photography/2020-06-01.png
    - packages/journal/assets/photography/2020-05-31.png
    - packages/journal/assets/photography/2020-05-25.png
    - packages/journal/assets/photography/2020-05-03.png
