name: journal
description: A multi-category blog journal built using Flutter.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.5955-rc.1
  iframes:
    path: ../iframes
  # unicorndial: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  assets:
    - packages/journal/assets/photography/2021-03-10.png
    - packages/journal/assets/photography/2021-02-10.png
    - packages/journal/assets/photography/2021-02-09.png
    - packages/journal/assets/photography/2021-02-06.png
    - packages/journal/assets/photography/2020-09-13.png
    - packages/journal/assets/photography/2020-09-11.png
    - packages/journal/assets/photography/2020-08-18.png
    - packages/journal/assets/photography/2020-08-10.png
    - packages/journal/assets/photography/2020-06-01.png
    - packages/journal/assets/photography/2020-05-31.png
    - packages/journal/assets/photography/2020-05-25.png
    - packages/journal/assets/photography/2020-05-03.png
