name: resume
description: A resume built using Flutter which is downloadable as a PDF.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  pdf: ^1.12.0
  printing: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
