name: resume
description: A resume built using Flutter which is downloadable as a PDF.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  pdf:
  printing:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
