name: publish_github_pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build + Publish Web
    env:
      USER_EMAIL: defuncart@gmail.com
      USER_NAME: "James Leahy"
      GH_USERNAME: defuncart
      REPO_NAME: defuncart.github.io
      PUBLISH_URL: defuncart.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install Jaspr
        run: dart pub global activate jaspr_cli
      - name: Dependencies
        run: dart pub get
      - name: Install Tailwind
        run: |
          # curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.17/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
          tailwindcss -h
      - name: Build + Commit
        run: |
          jaspr build -v
          cd build/jaspr
          git init
          git config --global user.email ${{ env.USER_EMAIL }}
          git config --global user.name ${{ env.USER_NAME }}
          echo ${{ env.PUBLISH_URL }} >CNAME
          echo "Autogenerated from https://github.com/${{ env.GH_USERNAME }}/${{ env.REPO_NAME }}/.">README.md
          git status
          git remote add origin https://${{ secrets.commit }}@github.com/${{ env.GH_USERNAME }}/${{ env.REPO_NAME }}.git
          git checkout -b gh-pages
          git add -A
          git commit -m "`date`"
          git push origin gh-pages -f
