name: pull_request
on: pull_request
jobs:
  lint-unit-test:
    name: Lint + Tests + Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install Jaspr
        run: dart pub global activate jaspr_cli
      - name: Dependencies
        run: dart pub get
      - name: Lint (Dart)
        run:  dart analyze
      - name: Lint (Jaspr)
        run:  jaspr analyze
      - name: Tests
        run: dart test
      - name: Build website
        run: jaspr build
